version: 2.1

# Orb definitions
orbs:
  continuation: circleci/continuation@0.2.0

# Define any filters, references, or cache keys
references:
  - &CERT_KEY certs-cache-{{ checksum "certs_cache_key" }}-v3

filters: &all_tags
  tags:
    only: /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

# Define jobs
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - maybe_build_certs
      - run:
          name: Generate config
          command: |
            tools/circle-generate-config.sh generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml

  runner-test:
    machine: true
    resource_class: scramble/apps  # Ensure this matches the resource class in CircleCI
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "Hello, World! I'm running on a self-hosted runner!"

commands:
  maybe_build_certs:
    steps:
      - run:
          name: Prepare cache key
          command: tools/make-certs-cache-key.sh > certs_cache_key && cat certs_cache_key
      - restore_cache:
          name: Restore certificates
          key: *CERT_KEY
      - run:
          name: Build certificates if not cached
          command: test -f tools/ssl/mongooseim/key.pem || make certs
      - run:
          name: Print cert hashes for debugging
          command: find tools/ssl -type f -exec md5sum {} \; | sort
      - run:
          name: Continue if certificate exists
          command: test -f tools/ssl/mongooseim/key.pem
      - save_cache:
          name: Cache built certs
          key: *CERT_KEY
          paths:
            - ~/project/tools/ssl/ca
            - ~/project/tools/ssl/ca-clients
            - ~/project/tools/ssl/mongooseim

# Define workflows
workflows:
  version: 2

  # Setup workflow to generate dynamic config
  setup:
    jobs:
      - setup:
          filters: *all_tags

  # Main testing workflow that runs on the self-hosted runner
  testing:
    jobs:
      - runner-test
